Implement get transaction by hash rpc endpoint
matter-labs/era-test-node pull request #22
Opened 2023-08-01 19:48 UTC by IAvecilla

# What :computer: 
* Implementation of `get_transaction_by_hash` RPC endpoint

# Why :hand:
* Some operations done in the [zksync-era Rust SDK](https://github.com/lambdaclass/zksync-web3-rs) need the implementation of this method to get the transaction receipts.

# Evidence :camera:
- 

# Notes :memo:
* This implementation may be incorrect and not entirely accurate. I used the other implementations as a reference.

2023-08-02 07:39 UTC, MexicanAce commented on src/node.rs
>      fn get_transaction_by_hash(
Looks good to me 👍 . Can we please move this function up above Line `755` now that it's implemented? (we have a split in this file above and below the `// Methods below are not currently implemented.` comment 😄 )

2023-08-02 15:07 UTC, MexicanAce commented
Can you please add Verification Evidence to the PR description? Perhaps screenshots of Rust SDK operations working with this change?

2023-08-02 15:18 UTC, MexicanAce requested changes
Can you please add Verification Evidence to the PR description? Perhaps screenshots of Rust SDK operations working with this change?

2023-08-02 18:49 UTC, faheelsattar commented
I am running my tests on hardhat and getting the same error when trying to call a contract function.
`
      await DAI.connect(this.signers.admin.address).mint(
      this.signers.admin.address,
      parseUnits("2000000", "18"),
    );
`
![image](https://github.com/matter-labs/era-test-node/assets/33996566/1d236967-40cf-4f4b-9dff-1e5d0f95c6f0)

2023-08-03 07:57 UTC, MexicanAce approved these changes
LGTM

2023-08-03 07:58 UTC, merged